export const FETCHING_CLASSES_START = 'FETCHING_CLASSES_START'
export const FETCHING_CLASSES_SUCCESS = 'FETCHING_CLASSES_SUCCESS'
export const FETCHING_CLASSES_ERROR = 'FETCHING_CLASSES_ERROR'

export const POSTING_CLASSES_START = 'POSTING_CLASSES_START'
export const POSTING_CLASSES_SUCCESS = 'POSTING_CLASSES_SUCCESS'
export const POSTING_CLASSES_ERROR = 'POSTING_CLASSES_ERROR'


export const DELETING_CLASSES_START = 'DELETING_CLASSES_START'
export const DELETING_CLASSES_SUCCESS = 'DELETING_CLASSES_SUCCESS'
export const DELETING_CLASSES_ERROR = 'DELETING_CLASSES_ERROR'

